### ISSUE TITLE
Build Deb failed

### ISSUE THREAD

**Issue by RemcoHalman** [ferstar/fbs_demo#1]
Hi @ferstar, thanks for the awesome project. Im running into a failing deb build with 
```bash
314 Successfully installed dotenv-2.8.1
315 Successfully installed pleaserun-0.0.32
Error: Process completed with exit code 1.
```

any ideas where to start?

**Comment by ferstar** [comment]
@RemcoHalman It looks like a problem caused by some software dependency update incompatibility, which I have fixed, see my commit log for details.
